/*
 * This source file was generated by the Gradle 'init' task
 */
package test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.lang.reflect.Method;



class AppTest {
    @Test void testStartsWithTest() {
        assertDoesNotThrow(() -> {
            Method startsWithTest = App.class.getDeclaredMethod("startsWithTest", String.class);
            startsWithTest.setAccessible(true);
            assertTrue((boolean)startsWithTest.invoke(null, "test4"));
            assertFalse((boolean)startsWithTest.invoke(null, " test4"));
        });
    }

}
